// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzeybLyEO-YSF7bB9lCcBwzq-zbyGpF2A',
    appId: '1:581417131832:web:e1454dbdf10941903debcd',
    messagingSenderId: '581417131832',
    projectId: 'app-gym-1942a',
    authDomain: 'app-gym-1942a.firebaseapp.com',
    storageBucket: 'app-gym-1942a.appspot.com',
    measurementId: 'G-PVNTP157BE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFL51fRpFYGeTGzJlOFUbJ68nolHkAsHM',
    appId: '1:581417131832:ios:1c57c076109258573debcd',
    messagingSenderId: '581417131832',
    projectId: 'app-gym-1942a',
    storageBucket: 'app-gym-1942a.appspot.com',
    iosBundleId: 'com.example.appGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFL51fRpFYGeTGzJlOFUbJ68nolHkAsHM',
    appId: '1:581417131832:ios:1c57c076109258573debcd',
    messagingSenderId: '581417131832',
    projectId: 'app-gym-1942a',
    storageBucket: 'app-gym-1942a.appspot.com',
    iosBundleId: 'com.example.appGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzeybLyEO-YSF7bB9lCcBwzq-zbyGpF2A',
    appId: '1:581417131832:web:7cf56933340efe733debcd',
    messagingSenderId: '581417131832',
    projectId: 'app-gym-1942a',
    authDomain: 'app-gym-1942a.firebaseapp.com',
    storageBucket: 'app-gym-1942a.appspot.com',
    measurementId: 'G-TXXCSSV5J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVFh1aRuIiH1rmK-Lo3xzsIIzemBwPtU',
    appId: '1:581417131832:android:deb6275871c76f873debcd',
    messagingSenderId: '581417131832',
    projectId: 'app-gym-1942a',
    storageBucket: 'app-gym-1942a.appspot.com',
  );

}